import {
    AMERICANO,
    CAFFELATTE,
    CAPPUCCINO,
    CAPPUCCINO_MIX,
    CAPPUCCINO_PLUS,
    CHOCOLATE_MIX_CARAFE,
    COFFEE,
    COFFEE_POT,
    COLD_AMERICANO,
    COLD_BREW,
    COLD_BREW_CAPPUCCINO,
    COLD_BREW_LATTE,
    COLD_BREW_POT,
    COLD_BREW_TO_MIX,
    COLD_CAFFELATTE,
    COLD_CAPPUCCINO,
    COLD_CAPPUCCINO_MIX,
    COLD_COFFEE,
    COLD_COFFEE_MIX_CARAFE,
    COLD_ESPRESSO,
    COLD_FLAT_WHITE,
    COLD_LATTE_MACCHIATO,
    COLD_MILK,
    COLD_MILK_FOAM_MIX_CARAFE,
    ColdCoffeeDrinksType,
    ColdMilkDrinksType,
    CORTADO,
    DOPPIO_PLUS,
    ESPRESSO,
    ESPRESSO_LUNGO,
    ESPRESSO_MACCHIATO,
    FLAT_WHITE,
    FOAMED_MILK,
    HOT_MILK,
    HOT_WATER,
    HotCoffeeDrinksType,
    HotMilkDrinksType,
    LATTE_MACCHIATO,
    LONG,
    LONG_BLACK,
    MUG_TO_GO,
    OtherDrinksType,
    OVER_ICE,
    STEAM,
    TEA_FUNCTION,
    TWO_CAPPUCCINO,
    TWO_CAPPUCCINO_MIX,
    TWO_LATTE_MACCHIATO,
} from './drinks';

export class CoffeeMachine {
    public technicalData: {
        dimensions: string;
        weight: number;
        pumpPressure: number;
        beansContainerCapacity: number;
        waterContainerCapacity: number;
        coffeeGrinder: 'металева конічна' | 'металева плоскопараллельна';
        degreesOfGrinding: number;
        groundsContainerCapacity: number;
        maxCupHeight: number;
        inputPower: number;
        ratedVoltageFrequency: string;
    };

    public colourMaterialFinish: {
        colour: string;
        finishing: string;
    };

    public functions: {
        hotCoffeeDrinks: HotCoffeeDrinksType;
        hotMilkDrinks: HotMilkDrinksType | null;
        coldCoffeeDrinks: ColdCoffeeDrinksType | null;
        coldMilkDrinks: ColdMilkDrinksType | null;
        otherDrinks: OtherDrinksType;
        totalCountOfDrinks: number;
        aromaFunction: boolean;
        possibilityToCustomiseLength: boolean;
        advancedPersonalisation: string | null;
        abilityToCreateYourOwnDrinks: string | null;
    };

    public controlPanel: {
        controls: string;
        display: string | null;
        connectivity: string | null;
    };

    public features: {
        milkSystem: string;
        possibilityToFrothMilkManually: boolean;
        beanAdapt: boolean;
        cupIllumination: boolean;
        cupWarmer: 'активний' | 'пасивний' | null;
        cupHolder: string;
        twinShot: boolean;
        thermalMilkJug: boolean;
    };

    public miscellaneous: {
        possibilityToUseWaterFilter: boolean;
        programmableWaterHardness: boolean;
        possibilityToUseGroundCoffee: boolean;
    };

    constructor(public model: string,
                public series: string,
                public imageUrl: string[],
                public videoId: string | null,
                public description: string | null,
                public summary: string[],
                dimensions: string,
                weight: number,
                pumpPressure: number,
                beansContainerCapacity: number,
                waterContainerCapacity: number,
                coffeeGrinder: 'металева конічна' | 'металева плоскопараллельна',
                degreesOfGrinding: number,
                groundsContainerCapacity: number,
                maxCupHeight: number,
                colour: string,
                finishing: string,
                hotCoffeeDrinks: HotCoffeeDrinksType,
                hotMilkDrinks: HotMilkDrinksType | null,
                coldCoffeeDrinks: ColdCoffeeDrinksType | null,
                coldMilkDrinks: ColdMilkDrinksType | null,
                otherDrinks: OtherDrinksType,
                advancedPersonalisation: string | null,
                abilityToCreateYourOwnDrinks: string | null,
                controls: string,
                display: string | null,
                connectivity: string | null,
                milkSystem: string,
                possibilityToFrothMilkManually: boolean,
                beanAdapt: boolean,
                cupIllumination: boolean,
                cupWarmer: 'активний' | 'пасивний' | null,
                cupHolder: string,
                thermalMilkJug: boolean) {
        this.technicalData = {
            dimensions,
            weight,
            pumpPressure,
            beansContainerCapacity,
            waterContainerCapacity,
            coffeeGrinder,
            degreesOfGrinding,
            groundsContainerCapacity,
            maxCupHeight,
            inputPower: this.model === 'EPAM960.75.GLM' ? 1550 : 1450,
            ratedVoltageFrequency: '220-240 V / 50-60 Hz',
        };

        this.colourMaterialFinish = {
            colour,
            finishing,
        };

        this.functions = {
            hotCoffeeDrinks,
            hotMilkDrinks,
            coldCoffeeDrinks,
            coldMilkDrinks,
            otherDrinks,
            totalCountOfDrinks: hotCoffeeDrinks.length + (hotMilkDrinks ? hotMilkDrinks.length : 0) + (coldCoffeeDrinks ? coldCoffeeDrinks.length : 0) + (coldMilkDrinks ? coldMilkDrinks.length : 0) + otherDrinks.length,
            aromaFunction: true,
            possibilityToCustomiseLength: true,
            advancedPersonalisation,
            abilityToCreateYourOwnDrinks,
        };

        this.controlPanel = {
            controls,
            display,
            connectivity,
        };

        this.features = {
            milkSystem,
            possibilityToFrothMilkManually,
            beanAdapt,
            cupIllumination,
            cupWarmer,
            cupHolder,
            twinShot: true,
            thermalMilkJug,
        };

        this.miscellaneous = {
            possibilityToUseWaterFilter: true,
            programmableWaterHardness: true,
            possibilityToUseGroundCoffee: true,
        };
    }
}

export const ecam650_85 = new CoffeeMachine('ECAM650.85.MS',
    'PrimaDonna Elite Experience',
    ['https://dam.delonghi.com/902x902/assets/84298', 'https://dam.delonghi.com/902x902/assets/186070', 'https://dam.delonghi.com/902x902/assets/84323', 'https://dam.delonghi.com/902x902/assets/95788'],
    'E3FpR6UzruA',
    'Підніміть приготування кави на новий рівень з PrimaDonna Elite Experience. Витончена обробка з нержавіючої сталі та яскравий сенсорний екран перш за все привернуть вашу увагу, а потім - її інноваційні функції. Підключіться через Bluetooth із додатком Coffee Link, щоб створювати й персоналізувати нові рецепти. Виберіть із широкого асортименту напоїв, щоб насолодитися улюбленою кавою вдома.',
    ['Напої на основі кави та молока одним дотиком', 'Приготування 2 чашок еспресо одночасно', 'Кремова, щільна, стійка молочна піна ідеальної температури за допомогою автоматичної системи LatteCrema System. Карафа для молока з автоматичним очищенням', 'Керуйте профілями, створюйте та налаштовуйте нові рецепти за допомогою дисплея та додатка Coffee Link', 'Корпус із нержавіючої сталі та кольоровий сенсорний дисплей'],
    '260 x 375 x 470',
    12.4,
    19,
    400,
    2,
    'металева конічна',
    13,
    14,
    142,
    'Металево-сріблястий',
    'Суцільно-металевий',
    [ESPRESSO, COFFEE, LONG, DOPPIO_PLUS, AMERICANO],
    [CAPPUCCINO, LATTE_MACCHIATO, CAPPUCCINO_PLUS, CAPPUCCINO_MIX, HOT_MILK, CAFFELATTE, FLAT_WHITE, ESPRESSO_MACCHIATO],
    null,
    null,
    [CHOCOLATE_MIX_CARAFE, COLD_COFFEE_MIX_CARAFE, COLD_MILK_FOAM_MIX_CARAFE, TEA_FUNCTION, HOT_WATER, STEAM],
    '6 профілів користувача + гостьовий профіль',
    'Так, через додаток',
    'Сенсорний дисплей',
    'кольоровий 4,3" TFT',
    'Coffee Link App',
    'LatteCrema Hot Technology',
    true,
    false,
    true,
    'активний',
    'Zamac',
    true);

export const ecam370_95 = new CoffeeMachine('ECAM370.95.T',
    'Dinamica Plus',
    ['https://dam.delonghi.com/902x902/assets/118864', 'https://dam.delonghi.com/902x902/assets/118841', 'https://dam.delonghi.com/902x902/assets/118871'],
    'iiXqD1Evr3w',
    'Обирайте з 12 рецептів і насолоджуйтесь смачним напоєм за допомогою автоматичної кавомашини Dinamica Plus. Цей незабутній кавовий досвід покращується унікальними інтерактивними функціями, включаючи Smart One Touch, 3 профілі користувачів і додаток Coffee Link для безмежної персоналізації. Ця кавомашина преміум-класу є обов’язковою на будь-якій сучасній кухні.',
    ['Напої на основі кави та молока одним дотиком', 'Приготування 2 чашок еспресо одночасно', 'Кремова, щільна, стійка молочна піна ідеальної температури за допомогою автоматичної системи LatteCrema System. Карафа для молока з автоматичним очищенням', 'Керуйте профілями, створюйте та налаштовуйте нові рецепти за допомогою дисплея та додатка Coffee Link', 'Преміальний титановий колір та 3,5-дюймовий сенсорний дисплей'],
    '236 x 429 x 348',
    9.5,
    19,
    300,
    1.8,
    'металева конічна',
    13,
    14,
    135,
    'Титановий',
    'Фарбований пластик',
    [ESPRESSO, COFFEE, LONG, DOPPIO_PLUS, COFFEE_POT],
    [CAPPUCCINO, LATTE_MACCHIATO, CAPPUCCINO_PLUS, CAPPUCCINO_MIX, HOT_MILK, CAFFELATTE, FLAT_WHITE, ESPRESSO_MACCHIATO],
    null,
    null,
    [HOT_WATER],
    '3 профілі користувача + гостьовий профіль',
    'Так, через додаток',
    'Сенсорний дисплей',
    'кольоровий 3,5" TFT',
    'Coffee Link App',
    'LatteCrema Hot Technology',
    false,
    false,
    false,
    'пасивний',
    'Нержавіюча сталь',
    true);

export const ecam370_70 = new CoffeeMachine('ECAM370.70.B',
    'Dinamica Plus',
    ['https://dam.delonghi.com/902x902/assets/219345', 'https://dam.delonghi.com/902x902/assets/125041', 'https://dam.delonghi.com/902x902/assets/186030', 'https://dam.delonghi.com/902x902/assets/192114', 'https://dam.delonghi.com/902x902/assets/219347'],
    'tjgYo4OD1rc',
    'Обирайте з 12 рецептів і насолоджуйтесь смачним напоєм за допомогою автоматичної кавомашини Dinamica Plus. Цей незабутній кавовий досвід покращується унікальними інтерактивними функціями, зокрема Smart One Touch для безмежної персоналізації. Елегантне чорне покриття неодмінно приверне вашу увагу.',
    ['Напої на основі кави та молока одним дотиком', 'Приготування 2 чашок еспресо одночасно', 'Кремова, щільна, стійка молочна піна ідеальної температури за допомогою автоматичної системи LatteCrema System. Карафа для молока з автоматичним очищенням', 'Елегантний чорний колір та 3,5-дюймовий сенсорний дисплей'],
    '236 x 429 x 348',
    9.5,
    19,
    300,
    1.8,
    'металева конічна',
    13,
    14,
    135,
    'Чорний',
    'Пластик',
    [ESPRESSO, COFFEE, LONG, DOPPIO_PLUS, COFFEE_POT],
    [CAPPUCCINO, LATTE_MACCHIATO, CAPPUCCINO_PLUS, CAPPUCCINO_MIX, HOT_MILK, CAFFELATTE, FLAT_WHITE, ESPRESSO_MACCHIATO],
    null,
    null,
    [HOT_WATER],
    'Функція "My"',
    null,
    'Сенсорний дисплей',
    'кольоровий 3,5" TFT',
    null,
    'LatteCrema Hot Technology',
    false,
    false,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

export const ecam22_112 = new CoffeeMachine('ECAM22.112.B',
    'Magnifica S',
    ['https://dam.delonghi.com/902x902/assets/223655', 'https://dam.delonghi.com/902x902/assets/148639', 'https://dam.delonghi.com/902x902/assets/148644', 'https://dam.delonghi.com/902x902/assets/71561'],
    'ol0PjrMxe6g',
    null,
    ['Напої на основі кави одним натисканням кнопки', 'Система Twin-Shot готує 2 чашки еспресо одночасно', 'Вершкова молочна піна зі спінювачем молока з ручним регулюванням', 'Можливість налаштування аромату та кількості напою', 'Чорний глянцевий корпус із сріблястою панеллю з кнопками з м\'яким натиском'],
    '230 x 430 x 340',
    9,
    15,
    250,
    1.8,
    'металева конічна',
    13,
    14,
    142,
    'Чорний',
    'Пластик',
    [ESPRESSO, ESPRESSO_LUNGO],
    null,
    null,
    null,
    [HOT_WATER, STEAM],
    null,
    null,
    'Кнопки',
    null,
    null,
    'Cappuccino System',
    true,
    false,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

export const ecam220_21 = new CoffeeMachine('ECAM220.21.B',
    'Magnifica Start',
    ['https://dam.delonghi.com/902x902/assets/246474', 'https://dam.delonghi.com/902x902/assets/218782', 'https://dam.delonghi.com/902x902/assets/236105', 'https://dam.delonghi.com/902x902/assets/244958', 'https://dam.delonghi.com/902x902/assets/246464', 'https://dam.delonghi.com/902x902/assets/244943'],
    'P6eZ5NceqGA',
    'Пориньте у світ кави у зернах разом із De\'Longhi Magnifica Start, що надає все необхідне для приготування улюблених напоїв на основі еспресо вдома. Вона має привабливу гладку чорну поверхню та оснащена зручним інтерфейсом з індивідуальним вибором напоїв, для приготування яких достатньо одного дотику.',
    ['Насолоджуйтесь улюбленими кавовими напоями зі свіжозмелених зерен', 'Можливість ручного приготування вершкової молочної піни за допомогою традиційного спінювача молока', 'Можливість вибирати з 4 рецептів одним дотиком: пара, еспресо, кава та доппіо+', 'Персоналізація аромату та температури напою', 'Знімні компоненти, які можна мити в посудомийній машині, для легкого догляду'],
    '240 x 440 x 350',
    8.8,
    15,
    250,
    1.8,
    'металева конічна',
    13,
    14,
    140,
    'Чорний',
    'Пластик',
    [ESPRESSO, COFFEE, DOPPIO_PLUS],
    null,
    null,
    null,
    [HOT_WATER, STEAM],
    null,
    null,
    'Сенсорні кнопки',
    null,
    null,
    'Cappuccino System',
    true,
    false,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

export const ecam220_60 = new CoffeeMachine('ECAM220.60.B',
    'Magnifica Start',
    ['https://dam.delonghi.com/902x902/assets/271841', 'https://dam.delonghi.com/902x902/assets/231606', 'https://dam.delonghi.com/902x902/assets/244958', 'https://dam.delonghi.com/902x902/assets/267855', 'https://dam.delonghi.com/902x902/assets/267857'],
    'rsmnAKyEDYw',
    'Пориньте у світ кави у зернах разом із De\'Longhi Magnifica Start, що надає все необхідне для приготування улюблених напоїв на основі еспресо вдома. Вона оснащена ексклюзивною технологією LatteCrema Hot, щоб наповнювати ваші напої насиченою молочною пінкою, а також має вибір напоїв, для приготування яких достатньо одного дотику.',
    ['Насолоджуйтесь улюбленими кавовими напоями зі свіжозмелених зерен', 'LatteCrema Hot наповнює ваші напої густою молочною піною та оснащена автоматичним очищенням одним дотиком', 'Можливість вибирати з 4 рецептів одним дотиком: еспресо, кава, капучіно та гаряча вода', 'Персоналізація аромату напою', 'Знімні компоненти, які можна мити в посудомийній машині, для легкого догляду'],
    '240 x 440 x 350',
    8.8,
    15,
    250,
    1.8,
    'металева конічна',
    13,
    14,
    140,
    'Чорний',
    'Пластик',
    [ESPRESSO, COFFEE],
    [CAPPUCCINO],
    null,
    null,
    [HOT_WATER],
    null,
    null,
    'Сенсорні кнопки',
    null,
    null,
    'LatteCrema Hot Technology',
    false,
    false,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

export const ecam290_21 = new CoffeeMachine('ECAM290.21.B',
    'Magnifica Evo',
    ['https://dam.delonghi.com/902x902/assets/228161', 'https://dam.delonghi.com/902x902/assets/218782', 'https://dam.delonghi.com/902x902/assets/218783', 'https://dam.delonghi.com/902x902/assets/218785', 'https://dam.delonghi.com/902x902/assets/218787'],
    'yiILFEek-NI',
    'Насолоджуйтеся неперевершеною кавою, не виходячи з дому, з De\'Longhi Magnifica Evo. Приготуйте ідеальний напій зі свіжозмелених зерен за допомогою одного із 4 рецептів, доступних одним дотиком. Кавомашина має інтуїтивно зрозумілу сенсорну панель керування із кольоровими значками для кожного рецепта. Її стильний чорний колір стане ідеальним доповненням до будь-якої сучасної кухні.',
    ['4 рецепти одним дотиком', 'Кремова молочна піна завдяки ручному спінювачу молока', 'Решітка, яку можна мити в посудомийній машині, і знімний заварювальний блок для легкого очищення', 'Сучасний дизайн із витонченою чорною обробкою'],
    '240 x 440 x 360',
    9.4,
    15,
    250,
    1.8,
    'металева конічна',
    13,
    14,
    140,
    'Чорний',
    'Пластик',
    [ESPRESSO, COFFEE, LONG],
    null,
    null,
    null,
    [HOT_WATER, STEAM],
    null,
    null,
    'Сенсорні кнопки',
    null,
    null,
    'Cappuccino System',
    true,
    false,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

export const ecam290_51 = new CoffeeMachine('ECAM290.51.B',
    'Magnifica Evo',
    ['https://dam.delonghi.com/902x902/assets/260898', 'https://dam.delonghi.com/902x902/assets/218787', 'https://dam.delonghi.com/902x902/assets/231606', 'https://dam.delonghi.com/902x902/assets/257394', 'https://dam.delonghi.com/902x902/assets/257395'],
    'duLoyCwcejI',
    'Magnifica Evo втілює досвід De\'Longhi завдяки своїм автентичним напоям і елегантному сучасному дизайну. Приготуйте ідеальний італійський еспресо обо один з інших напоїв, у тому числі доповнених молочною пінкою завдяки технології LatteCrema Hot. Вибирайте із 4 напоїв одним дотиком через простий інтерфейс користувача. А також кавомашина оснащена функцією автоматичного очищення молочника одним дотиком.',
    ['LatteCrema Hot доповнює ваші напої густою вершковою молочною пінкою', 'Оснащена функцією автоматичного очищення одним дотиком і карафою для молока, яку можна мити в посудомийній машині', 'Інтелектуальна панель керування з сенсорними піктограмами, включно з 4 варіантами напою одним дотиком', 'Додайте стилю своїй кухні за допомогою цієї витонченої чорної кавомашини'],
    '240 x 440 x 360',
    9.6,
    15,
    250,
    1.8,
    'металева конічна',
    13,
    14,
    140,
    'Чорний',
    'Пластик',
    [ESPRESSO, COFFEE],
    [LATTE_MACCHIATO],
    null,
    null,
    [HOT_WATER],
    null,
    null,
    'Сенсорні кнопки',
    null,
    null,
    'LatteCrema Hot Technology',
    false,
    false,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

// const ecam359_55

export const ecam450_65 = new CoffeeMachine('ECAM450.65.G',
    'Eletta Explore',
    ['https://dam.delonghi.com/902x902/assets/257455', 'https://dam.delonghi.com/902x902/assets/220127', 'https://dam.delonghi.com/902x902/assets/232723', 'https://dam.delonghi.com/902x902/assets/247339', 'https://dam.delonghi.com/902x902/assets/232717'],
    'MNrCaAKMFwE',
    'Нова автоматична кавомашина De\'Longhi Eletta Explore у вишуканому темно-сірому кольорі пропонує вам більше 50 гарячих і холодних напоїв.\n' +
    'Насолоджуйтеся автоматичною гарячою молочною пінкою завдяки LatteCrema Hot Technology і освіжаючими холодними кавовими напоями з LatteCrema Cool і Cold Extraction Technologies вдома чи в дорозі за допомогою зручної функції To-Go.',
    ['LatteCrema Hot та Cool Technologies для автоматичного гарячого та холодного спінювання молока', 'Технологія Cold Extraction для найбільш освіжаючих напоїв Cold Brew менш ніж за 5 хвилин', '3,5-дюймовий TFT-дисплей з кольоровими сенсорними іконками', 'Технологія Bean Adapt автоматично регулює параметри машини для кожного типу кави, щоб забезпечити ідеальну екстракцію кави', 'З’єднання через Wi-Fi і мобільний додаток', 'Автоматична система To-Go для чашок висотою до 16 см'],
    '260 x 450 x 385',
    11.3,
    19,
    300,
    1.8,
    'металева конічна',
    13,
    14,
    170,
    'Сірий',
    'Фарбований пластик з металевими елементами',
    [ESPRESSO, COFFEE, LONG, DOPPIO_PLUS, COFFEE_POT],
    [CAPPUCCINO, LATTE_MACCHIATO, CAPPUCCINO_PLUS, CAPPUCCINO_MIX, HOT_MILK, CAFFELATTE, FLAT_WHITE, CORTADO, ESPRESSO_MACCHIATO],
    [COLD_AMERICANO, COLD_COFFEE, COLD_ESPRESSO, COLD_BREW, COLD_BREW_TO_MIX, COLD_BREW_POT],
    [COLD_CAPPUCCINO, COLD_CAPPUCCINO_MIX, COLD_LATTE_MACCHIATO, COLD_CAFFELATTE, COLD_MILK, COLD_FLAT_WHITE, FOAMED_MILK, COLD_BREW_LATTE, COLD_BREW_CAPPUCCINO],
    [HOT_WATER],
    '4 профілі користувача + гостьовий профіль',
    'Так, через додаток',
    'Сенсорний дисплей',
    'кольоровий 3,5" TFT',
    'Coffee Link App',
    'LatteCrema Hot Technology, LatteCrema Cool Technology',
    false,
    true,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

export const ecam450_86 = new CoffeeMachine('ECAM450.86.T',
    'Eletta Explore',
    ['https://dam.delonghi.com/902x902/assets/257457', 'https://dam.delonghi.com/902x902/assets/220127', 'https://dam.delonghi.com/902x902/assets/220214', 'https://dam.delonghi.com/902x902/assets/232723', 'https://dam.delonghi.com/902x902/assets/247348', 'https://dam.delonghi.com/902x902/assets/232717'],
    'Y38FsqAokno',
    'Понад 50 гарячих і холодних напоїв із автоматичною кавомашиною De\'Longhi Eletta Explore у титановому оздобленні.\n' +
    'Насолоджуйтесь автоматичним приготуванням гарячої молочної піни завдяки технології LatteCrema Hot Technology і освіжаючими холодними та холодно-завареними кавовими напоями завдяки технологіям LatteCrema Cool і Cold Extraction.\n' +
    'Насолоджуйтесь власною кав’ярнею вдома та в дорозі за допомогою функції To-Go.',
    ['LatteCrema Hot та Cool Technologies для автоматичного гарячого та холодного спінювання молока', 'Технологія Cold Extraction для найбільш освіжаючих напоїв Cold Brew менш ніж за 5 хвилин', '3,5-дюймовий TFT-дисплей з кольоровими сенсорними іконками', 'Технологія Bean Adapt автоматично регулює параметри машини для кожного типу кави, щоб забезпечити ідеальну екстракцію кави', 'З’єднання через Wi-Fi і мобільний додаток', 'Автоматична система To-Go для чашок висотою до 16 см - чашка-аксесуар для подорожей у комплекті'],
    '260 x 450 x 385',
    11.3,
    19,
    300,
    1.8,
    'металева конічна',
    13,
    14,
    170,
    'Титановий',
    'Фарбований пластик з металевими елементами',
    [ESPRESSO, COFFEE, LONG, DOPPIO_PLUS, COFFEE_POT, AMERICANO],
    [CAPPUCCINO, LATTE_MACCHIATO, CAPPUCCINO_PLUS, CAPPUCCINO_MIX, HOT_MILK, CAFFELATTE, FLAT_WHITE, CORTADO, ESPRESSO_MACCHIATO],
    [COLD_AMERICANO, COLD_COFFEE, COLD_ESPRESSO, COLD_BREW, COLD_BREW_TO_MIX, COLD_BREW_POT],
    [COLD_CAPPUCCINO, COLD_CAPPUCCINO_MIX, COLD_LATTE_MACCHIATO, COLD_CAFFELATTE, COLD_MILK, COLD_FLAT_WHITE, FOAMED_MILK],
    [HOT_WATER],
    '4 профілі користувача + гостьовий профіль',
    'Так, через додаток',
    'Сенсорний дисплей',
    'кольоровий 3,5" TFT',
    'Coffee Link App',
    'LatteCrema Hot Technology, LatteCrema Cool Technology',
    true,
    true,
    false,
    'пасивний',
    'Нержавіюча сталь',
    false);

export const ecam610_74 = new CoffeeMachine('ECAM610.74.MB',
    'PrimaDonna Soul',
    ['https://dam.delonghi.com/902x902/assets/190115', 'https://dam.delonghi.com/902x902/assets/190129', 'https://dam.delonghi.com/902x902/assets/191135', 'https://dam.delonghi.com/902x902/assets/191143', 'https://dam.delonghi.com/902x902/assets/191147'],
    'Lp9MzaP9wto',
    'З новою De\'Longhi PrimaDonna Soul ви зможете відчути справжній аромат ваших улюблених кавових зерен. Завдяки інноваційній технології Bean Adapt, машина легко встановлює певний розмір помелу та параметри заварювання, щоб виконати індивідуальну екстракцію кави на основі вибраних вами зерен і надати весь їхній аромат прямо у вашу чашку.',
    ['Технологія Bean Adapt для персоналізації налаштувань машини відповідно до ваших кавових зерен', 'Кремова, щільна, стійка молочна піна ідеальної температури з автоматичною системою LatteCrema', 'До 21 напою одним натисканням кнопки', 'Повністю сенсорний кольоровий TFT-дисплей із діагоналлю 4,3 дюйма та можливість підключення до додатку Coffee Link для максимальної взаємодії'],
    '262 x 485 x 390',
    13,
    19,
    500,
    2.2,
    'металева плоскопараллельна',
    7,
    14,
    140,
    'Металево-чорний',
    'Пластик з металевими елементами',
    [ESPRESSO, COFFEE, LONG, DOPPIO_PLUS, COFFEE_POT, OVER_ICE, LONG_BLACK, AMERICANO],
    [CAPPUCCINO, LATTE_MACCHIATO, CAPPUCCINO_PLUS, CAPPUCCINO_MIX, HOT_MILK, CAFFELATTE, FLAT_WHITE, CORTADO, ESPRESSO_MACCHIATO],
    null,
    null,
    [MUG_TO_GO, TEA_FUNCTION, HOT_WATER],
    '5 профілів користувача + гостьовий профіль',
    'Так, через додаток',
    'Сенсорний дисплей',
    'кольоровий 4,3" TFT',
    'Coffee Link App',
    'LatteCrema Hot Technology',
    false,
    true,
    false,
    'пасивний',
    'Нержавіюча сталь',
    true);

export const epam960_75 = new CoffeeMachine('EPAM960.75.GLM',
    'Maestosa',
    ['https://dam.delonghi.com/902x902/assets/122189', 'https://dam.delonghi.com/902x902/assets/122160', 'https://dam.delonghi.com/902x902/assets/122162', 'https://dam.delonghi.com/902x902/assets/122165', 'https://dam.delonghi.com/902x902/assets/123529'],
    'kbhSGl5Xr_c',
    'Автоматична кавомашина Maestosa бездоганно поєднує в собі передові технології та привабливий дизайн. Яскраве дзеркальне чорне скло робить передню частину особливо вражаючою. Готуйте різноманітні персоналізовані напої з точним помелом і ідеальною кремовою молочною пінкою. Виберіть із 2 кавових сумішей і готуйте 2 чашки вашої улюбленої кави одночасно, щоб поділитися враженнями від De\'Longhi.',
    ['Технологія адаптивного помелу для точного електронного помелу кави', '2 окремих контейнера для зерен та дві кавомолки', 'Кремова, щільна, стійка молочна піна ідеальної температури з автоматичною системою LatteCrema', 'Карафа для молока для приготування 2 напоїв на основі молока одночасно', 'Керуйте профілями, створюйте та налаштовуйте рецепти за допомогою дисплею та додатку Coffee Link'],
    '290 x 468 x 405',
    16.8,
    19,
    580,
    2.1,
    'металева плоскопараллельна',
    7,
    18,
    142,
    'Металево-чорний',
    'Метал та скло',
    [ESPRESSO, COFFEE, LONG, DOPPIO_PLUS, COFFEE_POT, AMERICANO],
    [CAPPUCCINO, TWO_CAPPUCCINO, LATTE_MACCHIATO, TWO_LATTE_MACCHIATO, CAPPUCCINO_PLUS, CAPPUCCINO_MIX, TWO_CAPPUCCINO_MIX, HOT_MILK, CAFFELATTE, FLAT_WHITE, ESPRESSO_MACCHIATO],
    null,
    null,
    [CHOCOLATE_MIX_CARAFE, COLD_COFFEE_MIX_CARAFE, COLD_MILK_FOAM_MIX_CARAFE, TEA_FUNCTION, HOT_WATER, STEAM],
    '6 профілів користувача + гостьовий профіль',
    'Так, через додаток',
    'Сенсорний дисплей',
    'кольоровий 5" TFT',
    'Coffee Link App',
    'LatteCrema Hot Technology',
    true,
    false,
    true,
    'пасивний',
    'Нержавіюча сталь',
    true);